### ISSUE TITLE
gabisa input pw

### ISSUE THREAD

**Issue by MUHAMMADEFAN11** [PrastianHD/plume-testnet#1]
bre gabisa input password
![Screenshot 2024-07-22 113321](https://github.com/user-attachments/assets/fe620914-257f-4018-9562-a4edeb9266f3)

**Comment by PrastianHD** [comment]
Password : PlumesGOON

**Comment by MUHAMMADEFAN11** [comment]
mantap bisa, thanks bg

**Comment by PrastianHD** [comment]
Oke sama smaa
