### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by reysilvano78** [PrastianHD/plume-testnet#14]
need to put more then 1 proxy?

**Comment by PrastianHD** [comment]
proxy is needed if you run multi-account

**Comment by reysilvano78** [comment]
> proxy is needed if you run multi-account

i mean if i have 4 account does it mean i need to put 4 different proxy in file proxy.txt?

**Comment by PrastianHD** [comment]
Yes

Pada Min, 28 Jul 2024, 18.37, reysilvano78 ***@***.***>
menulis:
