### ISSUE TITLE
Gabisa claim faucet ETH

### ISSUE THREAD

**Issue by MUHAMMADEFAN11** [PrastianHD/plume-testnet#2]
error mulu kalau claim faucet eth, tpi klo yg goon aman aja
![Screenshot 2024-07-22 152655](https://github.com/user-attachments/assets/ad7d6043-6e25-45ad-958f-56880aac0772)

**Comment by PrastianHD** [comment]
tunggu 10 menit lagi mas, itu udah pernah claim

**Comment by MUHAMMADEFAN11** [comment]
Yes!

**Comment by cedok123** [comment]
pake password ya sir?

**Comment by PrastianHD** [comment]
Iya

Pada Sel, 23 Jul 2024, 09.20, cedok123 ***@***.***> menulis:

**Comment by cedok123** [comment]
passwordnya mau dong sir

**Comment by PrastianHD** [comment]
PLumesGOON

**Comment by cedok123** [comment]
thankyou sir

**Comment by cedok123** [comment]
![image](https://github.com/user-attachments/assets/3e143756-241a-4b06-8a96-d8d594a35270)
gabisa sir

**Comment by PrastianHD** [comment]
PlumesGOON,
