### ISSUE TITLE
Error File env

### ISSUE THREAD

**Issue by Ersa19** [PrastianHD/plume-testnet#3]
![Screenshot_2024-07-24-01-42-04-093_com termux](https://github.com/user-attachments/assets/cf64f16e-b76b-428d-8432-deec49b310dc)

Ketika run error dan muncul notif: Error parsing PRIVATE_KEYS: "undefined" is not valid JSON
Padahal saya sudah buat file .env.PRIVATE_KEYS, tapi tetap error.

**Comment by PrastianHD** [comment]
nama file .env isinya PRIVATE_KEYS

**Comment by Ersa19** [comment]
> nama file .env isinya PRIVATE_KEYS

Terima kasih. Work.
Tapi saat menggunakan menu faucet Goon, error Invalid Admin Signature

**Comment by PrastianHD** [comment]
Detek IP itu, ganti IP

Pada Rab, 24 Jul 2024, 06.05, Ersa19 ***@***.***> menulis:

**Comment by cedok123** [comment]
vpn kah?
