### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by 0xfarmed** [PrastianHD/plume-testnet#6]
Getting below error when running npm install

npm warn tarball tarball data for @crocswap-libs/sdk@file:sdk (null) seems to be corrupted. Trying again.
npm warn tarball tarball data for @crocswap-libs/sdk@file:sdk (null) seems to be corrupted. Trying again.
npm error code ENOENT
npm error syscall open
npm error path /root/plume-testnet/sdk/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/root/plume-testnet/sdk/package.json'
npm error enoent This is related to npm not being able to find a file.

**Comment by Ersa19** [comment]
sama mas, solusinya apa ya?
