### ISSUE TITLE
Error Saat Menjalankan Script

### ISSUE THREAD

**Issue by Ersa19** [PrastianHD/plume-testnet#7]
Saat menjalankan tiap fungsi yang ada pada script selalui error dan errornya sama, yatu INVALID ARGUE (error lengkap dapat dilihat di bagian bahwah). Apakah ada module yang kurang tepat atau perlu saya install? Tapi saat menjalankan npm install, selalu muncul error seperti error nomor 1 di bawah. Mohon bantuannya, terima kasih

**1. npm install**
npm warn tarball tarball data for @crocswap-libs/sdk@file:sdk (null) seems to be corrupted. Trying again.
npm warn tarball tarball data for @crocswap-libs/sdk@file:sdk (null) seems to be corrupted. Trying again.
npm error code ENOENT
npm error syscall open
npm error path F:\ScriptBotTele\PlumeNFTTestnet\v2\plume-testnet-main\sdk\package.json
npm error errno -4058
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open 'F:\ScriptBotTele\PlumeNFTTestnet\v2\plume-testnet-main\sdk\package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: C:\Users\ersan\AppData\Local\npm-cache\_logs\2024-07-24T10_16_15_046Z-debug-0.log

**2. CheckIn**
TypeError: invalid BytesLike value (argument="value", value="0x[\"9a95c654b93d3e1e56dd746ea5ae744173033231a39663b916c4cc08662e80ff\"", code=INVALID_ARGUMENT, version=6.13.1)

**3. Claim Faucet ETH**
24/07/2024, 17:08:59 | ERROR  | Error: invalid BytesLike value (argument="value", value="0x[\"9a95c654b93d3e1e56dd746ea5ae744173033231a39663b916c4cc08662e80ff\"", code=INVALID_ARGUMENT, version=6.13.1). Retrying 1/3 in 2 seconds...

**4. Claim Faucet GOON**
24/07/2024, 17:09:14 | ERROR  | Error: invalid BytesLike value (argument="value", value="0x[\"9a95c654b93d3e1e56dd746ea5ae744173033231a39663b916c4cc08662e80ff\"", code=INVALID_ARGUMENT, version=6.13.1). Retrying 1/3 in 2 seconds...

**5. Predict ETH/BTC/ARB** 
24/07/2024, 17:09:30 | ERROR  | Critical error: invalid BytesLike value (argument="value", value="0x[\"9a95c654b93d3e1e56dd746ea5ae744173033231a39663b916c4cc08662e80ff\"", code=INVALID_ARGUMENT, version=6.13.1)

**6. Create Asset Tokenized**
24/07/2024, 17:09:41 | ERROR  | Critical error: invalid BytesLike value (argument="value", value="0x[\"9a95c654b93d3e1e56dd746ea5ae744173033231a39663b916c4cc08662e80ff\"", code=INVALID_ARGUMENT, version=6.13.1)

**Comment by 0xfarmed** [comment]
have the exact same issue @PrastianHD

**Comment by QuantumLeap-us** [comment]
me too

**Comment by PrastianHD** [comment]
Coba install ulang guys, hapus folder dan clone ulang repo

**Comment by QuantumLeap-us** [comment]
![image](https://github.com/user-attachments/assets/7b20e971-40aa-4398-83c0-34d9833d582e)
It's the same mistake. I've tried different environments.

**Comment by QuantumLeap-us** [comment]
![image](https://github.com/user-attachments/assets/4718b88b-91c0-4ef3-bb87-d6ee6164dc61)
No access code Code is not open source Suggest you modify package.json

**Comment by QuantumLeap-us** [comment]
`{
  "name": "plume-testnet",
  "version": "1.8.0",
  "description": "Script All In One for Plume Testnet",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js"
  },
  "keywords": [],
  "author": "Prastian Hidayat",
  "repository": "https://github.com/PrastianHD/plume-testnet.git",
  "license": "MIT",
  "dependencies": {
    "@crocswap-libs/sdk": "^1.0.2",
    "axios": "^1.7.2",
    "chalk": "^4.1.2",
    "dotenv": "^16.4.5",
    "ethers": "^6.13.1",
    "moment": "^2.30.1",
    "readline-sync": "^1.4.10"
  }
}`
